name: Deploy

on:
  push:
    branches:
      
main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout code
      uses: actions/checkout@v2

      
name: Setup SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'rm -rf /home/Sasha/botscr && mkdir -p /home/Sasha/botscr && git clone https://github.com/NOSLEEPC0DER/testCICD.git /home/Sasha/botscr'
